name: Update JSON

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update JSON
      run: echo '[{"nome": "Exemplo", "dataHora": "2024-01-20T12:00:00"}]' > dados.json
